config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get '/home', to: 'pages#home', as: 'home'
  get '/menu', to: 'pages#menu', as: 'menu'
  get '/community', to: 'pages#community', as: 'community'
  get '/catering', to: 'pages#catering', as: 'catering'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/partners', to: 'pages#partners', as: 'partners'
  get '/privacy', to: 'pages#privacy', as: 'privacy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def menu
  end

  def community
  end

  def catering
  end

  def contact
  end

  def partners
  end

  def privacy
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="sunburst">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Voltaire&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Atlas Pizza Static Site Clone</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'header' %>
      <%= yield %>
      <%= render 'footer' %>
    </div>
  </body>

  <!-- Bootstrap script -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</html>

app/views/pages/_footer.html.erb
<br>
<div class="text-center">
  <br>
  <%= link_to 'Contact', contact_path, class: "footer-link" %> -
  <%= link_to 'Partners', partners_path, class: "footer-link" %> -
  <%= link_to 'Privacy', privacy_path, class: "footer-link" %>
  <br>
  © Atlas Pizza, Portland, Oregon
  <br><br>
</div>
<br>

app/views/pages/_header.html.erb
<div class="site-nav text-center">
  <%= link_to root_path do %>
    <br>
    <%= image_tag image_path('banner.png'), class: "img-fluid" %>
  <% end %>
  <%= link_to 'MENU', menu_path, class: 'site-nav-link' %>
  <%= link_to 'COMMUNITY', community_path, class: 'site-nav-link vert-divider-left' %>
  <%= link_to 'CATERING', catering_path, class: 'site-nav-link vert-divider-left' %>
  <%= link_to 'CONTACT', contact_path, class: 'site-nav-link vert-divider-left site-nav-last-link' %>
</div>

<nav class="navbar-ap">
  <div class="navbar-container-ap">
    <div class="navbar-header-ap">
      <div class="navbar-brand-container">
        <%= link_to "ATLAS PIZZA", root_path, class: 'navbar-brand-link' %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerLinks" aria-controls="navbarTogglerLinks" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse-ap" id="navbarTogglerLinks">
      <div class="nav-list-container">
        <ul class="navbar-nav-ap">
          <%# Only render a homepage link if not on the homepage %>
          <% unless current_page?(controller: 'pages', action: 'home') %>
            <li class="nav-item-ap">
              <%= link_to "Home Page", root_path, class: "nav-link-ap" %>
            </li>
          <% end %>
          <li class="nav-item-ap">
            <a class="nav-link-ap">ORDER ONLINE</a>
          </li>
          <li class="nav-item-ap">
            <%= link_to "Menu", menu_path, class: "nav-link-ap" %>
          </li>
          <li class="nav-item-ap">
            <%= link_to "Community", community_path, class: "nav-link-ap" %>
          </li>
          <li class="nav-item-ap">
            <%= link_to "Catering", catering_path, class: "nav-link-ap" %>
          </li>
          <li class="nav-item-ap">
            <%= link_to "Contact", contact_path, class: "nav-link-ap" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/pages/catering.html.erb
<div class="row">
  <div class="col-lg-1 col-xl-2"></div>
  <div class="col-xs-12 col-lg-10 col-xl-8">
    <br>
    <p>We offer 25% off all orders of 5 pies or more, with 24 hours notice. Fill out the form below, and we’ll contact you immediately!</p>

    <p class="form-title">CATERING ORDER FORM</p>
    <%= render 'pages/forms/catering_form' %>
  </div>
  <div class="col-lg-1 col-xl-2"></div>
</div>

app/views/pages/community.html.erb
<div class="row">
  <div class="col-xs-12">
    <br>
    <%= image_tag image_path("community/intro"), class: "img-fluid w-100" %>
    <br><br>
    <div class="text-center">
      <a class="square-btn">SIGN UP FOR OUR NEWSLETTER</a>
    </div>
    <br>
    <%= image_tag image_path("community/banner-pie-program"), class: "img-fluid w-100" %>
  </div>
</div>
<div class="row">
  <div class="col-lg-1 col-xl-2"></div>
  <div class="col-xs-12 col-lg-10 col-xl-8">
    <br>
    WE WANTED A WAY TO GIVE BACK, SO WE CAME UP WITH THE P.I.E. PROGRAM (PORTLAND INVESTS IN EDUCATION).
    WE DONATE 20% OF OUR PROFITS ON A CHOSEN EVENING TO A LOCAL SCHOOOL, FOR THEM TO USE IN WHATEVER WAY THEY NEED.
    PUBLIC SCHOOLS NEED ALL THE HELP THEY CAN GET, AND WE'RE HAPPY TO BE IN A POSITION TO GIVE BACK!
    IF YOU ARE AN EDUCATOR OR PARENT AND WOULD LIKE TO GET YOUR SCHOOL INVOLVED,
    PLEASE FILL OUT THE FORM BELOW.
    <br><br>
    <%= render 'pages/forms/community_form' %>
  </div>
  <div class="col-lg-1 col-xl-2"></div>
</div>
<div class="row">
  <div class="col-xs-12">
    <br><br>
    <%= image_tag image_path("community/banner-monthly-craft-nights"), class: "img-fluid w-100" %>
    <br><br>
    <%= link_to "https://collagepdx.blogspot.com/", target: "_blank" do %>
      <%= image_tag image_path("community/collage"), class: "img-fluid collage-img" %>
    <% end %>
    <br>
    WE'VE PARTNERED WITH LOCAL CRAFT STORE COLLAGE
    TO BRING MONTHLY CRAFT NIGHTS TO ALL OUR LOCATIONS.
    EVERY THIRD WEEK OF THE MONTH, COLLAGE'S TEAM BRINGS
    ALL THE SUPPLIES NEEDED TO CREATE A CRAFT OF THEIR CHOOSING.
    ALL SUPPLIES PROVIDED FREE, AND ALL AGES AND SKILL LEVELS WELCOME!
    <%= link_to "collagepdx.blogspot.com", "https://collagepdx.blogspot.com/", target: "_blank"%>
    <br><br>
    <%= image_tag image_path("community/banner-donations"), class: "img-fluid w-100" %>
    <br><br>
    WE'RE ALWAYS LOOKING FOR GOOD CAUSES TO DONATE FOOD TO.
    WE'LL ADMIT, SOMETIMES THERE'S A LOT OF SLICES LEFT OVER AT THE END OF THE NIGHT!
    WE DONATE THIS TO WASTE NOT FOOD TAXI, A LOCAL ORGANIZATION THAT AIMS TO REDUCE FOOD WASTE, WHENEVER WE CAN.
    IF YOU HAVE A CAUSE OR ORGANIZATION THAT IS INTERESTED IN A DONATION OF ANY KIND,
    FEEL FREE TO EMAIL US AT <%# Email address missing on actual site %>.
  </div>
</div>

app/views/pages/contact.html.erb
<div class="text-center">
  <br>

  <a class="square-btn">CALL 503-232-3004</a>
  <br><br>

  <a class="cursor-pointer">
    <%= image_tag image_path('contact/email-button'), class: "img-fluid contact-btn" %>
  </a>
  <div class="contact-btn-spacer"><br></div>

  <%= link_to "https://www.facebook.com/atlaspizzaportland/", target: "_blank" do %>
    <%= image_tag image_path('contact/contact-button-facebook'), class: "img-fluid contact-btn" %>
  <% end %>
  <div class="contact-btn-spacer"><br></div>

  <%= link_to "https://www.instagram.com/atlaspizzapdx/", target: "_blank" do %>
    <%= image_tag image_path('contact/contact-button-instagram'), class: "img-fluid contact-btn" %>
  <% end %>
  <div class="contact-btn-spacer"><br></div>

  <%= link_to "https://www.twitter.com/atlaspizzapdx/", target: "_blank" do %>
    <%= image_tag image_path('contact/contact-button-twitter'), class: "img-fluid contact-btn" %>
  <% end %>
  <br><br>

  <div class="text-center">
    <a class="square-btn">
      SIGN UP FOR OUR NEWSLETTER
    </a>
  </div>
  <br>

  <div class="location-header">
    3570 SE Division St, Portland, OR 97202
  </div>
  Daily 4-10pm
  <br>
  <%= image_tag image_path('contact/location-division'), class: "img-fluid" %>
  <br><br>

  <div class="location-header">
    710 N Killingsworth, Portland, OR 97217
  </div>
  Daily 4-10pm
  <br>
  <%= image_tag image_path('contact/location-killingsworth'), class: "img-fluid" %>
  <br><br>

  <div class="location-header">
    6529 SE Foster Rd, Portland, OR 97206
  </div>
  Daily 4-10pm
  <br>
  <%= image_tag image_path('contact/location-foster'), class: "img-fluid" %>
</div>

app/views/pages/forms/_catering_form.html.erb
<div class="form-container">
  <form>
    <div class="form-group">
      <%= label_tag 'name', 'YOUR FULL NAME', class: 'form-label' %>
      <%= text_field_tag 'name', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'phone', 'PHONE NUMBER', class: 'form-label' %>
      <%= text_field_tag 'phone', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'email', 'EMAIL', class: 'form-label' %>
      <%= text_field_tag 'email', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'date', 'DATE/TIME OF DELIVERY', class: 'form-label' %>
      <%= datetime_field_tag 'date', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'location', 'LOCATION OF DELIVERY', class: 'form-label' %>
      <%= text_field_tag 'location', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'notes', 'NOTES/REQUESTS', class: 'form-label' %>
      <%= text_area_tag 'notes', nil, rows: 4, class: 'form-control form-text-area' %>
    </div>
    <div class="form-group">
      <%= label_tag 'nospam', 'Select the pie that has no toppings:', class: 'form-label' %>
      <%= select_tag 'nospam', options_for_select($TOPPINGS), class: 'form-select form-control' %>
      <span id="nospamHelpBlock" class="help-block">(This is to prevent spam, which btw is not a topping at Atlas!)</span>
    </div>
    <div class="form-group">
      <a class="btn btn-success form-btn disabled">SEND</a>
    </div>
  </form>
</div>

app/views/pages/forms/_community_form.html.erb
<% $TOPPINGS = ['Green Pepper', 'Mushroom', 'Cheese', 'Pepperoni'] %>

<div class="form-container">
  <form>
    <div class="form-group">
      <%= label_tag 'name', 'YOUR FULL NAME', class: 'form-label' %>
      <%= text_field_tag 'name', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'school', 'ASSOCIATED SCHOOL', class: 'form-label' %>
      <%= text_field_tag 'school', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'phone', 'PHONE NUMBER', class: 'form-label' %>
      <%= text_field_tag 'phone', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'email', 'EMAIL', class: 'form-label' %>
      <%= text_field_tag 'email', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'nospam', 'Select the pie that has no toppings:', class: 'form-label' %>
      <%= select_tag 'nospam', options_for_select($TOPPINGS), class: 'form-select form-control' %>
      <span id="nospamHelpBlock" class="help-block">(This is to prevent spam, which btw is not a topping at Atlas!)</span>
    </div>
    <div class="form-group">
      <a class="btn btn-success form-btn disabled">SEND</a>
    </div>
  </form>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-xs-12 col-lg-8">
    <br>
    <p>
      Attention Atlas Pizza Friends!
      <br><br>
      It is with great pride that we announce the reopening of ALL our locations! Now open from 4pm to 10pm every day!
      <br><br>
      We will be serving our full menu for take out only! Whole pies at all locations, slices at Division and Foster,
      and everything else from our amazing knots, to our stuffed knots, to those Ceasar salads you’ve all been craving!
      <br><br>
      We are following safe practices to ensure our staffs safety and our customers safety as well. This includes social distancing, proper hand washing and sanitizing, and cooking our pizzas in 550 degree ovens. We take our own, and your safety as our number one priority.
      <br><br>
      Please call ahead to place an order. We are limited in our capabilities due to the amount of staff we can safely have on. This means we will be on a first call, first serve basis. Our online ordering system is available, but we prefer you call if possible. We also deliver through third party systems like Grubhub, Caviar and Postmates. While we would love for you to get Atlas Pizza in any way, please note that ordering directly through us is our preferred choice to provide for you, as that means all your money stays right here in our community.
      <br><br>
      Hang in there Portland!!! It’s going to take the entire community to get through this. We hope you are all safe and healthy and we can’t wait to see you!
      <br><br>
      Best wishes,
      <br>
      Johnny Ricci, Eli Johnson
      <br>
      Owners Atlas Pizza
    </p>
  </div>
  <div class="col-lg-2"></div>
</div>
<div class="row">
  <div class="col-lg-1"></div>
  <div class="col-xs-12 col-lg-6">
    <br>
    <div id="pizza-carousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag image_path('pizza_carousel/1'), class: 'd-block w-100' %>
        </div>
        <div class="carousel-item">
          <%= image_tag image_path('pizza_carousel/2'), class: 'd-block w-100' %>
        </div>
        <div class="carousel-item">
          <%= image_tag image_path('pizza_carousel/3'), class: 'd-block w-100' %>
        </div>
        <div class="carousel-item">
          <%= image_tag image_path('pizza_carousel/4'), class: 'd-block w-100' %>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#pizza-carousel"  data-bs-slide="prev">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 1792 1792"><path d="M1427 301l-531 531 531 531q19 19 19 45t-19 45l-166 166q-19 19-45 19t-45-19l-742-742q-19-19-19-45t19-45l742-742q19-19 45-19t45 19l166 166q19 19 19 45t-19 45z" fill="white"
        stroke-linecap="square"/></svg>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#pizza-carousel"  data-bs-slide="next">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 1792 1792"><path d="M1363 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45l166-166q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z" fill="white"
        stroke-linecap="square"/></svg>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <div class="col-xs-12 col-lg-4">
    <br>
    <div class="text-center">
      <%# Dummy links to avoid accidental calls and because I didn't implement the order interface (for obvious reasons) %>
      <a class='square-btn square-btn-left'>ORDER</a>
      <a class='square-btn square-btn-right'>CALL</a>
    </div>
    <br>
    <p>
        SINCE 2013, ATLAS PIZZA HAS BEEN DEDICATED TO SERVING OUR COMMUNITY, BRINGING YOU THE BEST PIES IN TOWN, AS WELL AS BEER AND WINE DELIVERY.
        ATLAS STRIVES TO BRING PORTLAND TOGETHER THROUGH GOOD FOOD, DRINKS, AND ROCK ’N ROLL HISTORY AT ALL 3 OF OUR UNIQUE LOCATIONS.
    </p>
  </div>
  <div class="col-lg-1"></div>
</div>
<div class="row">
  <div class="col-xs-12 col-lg-6">
    <br>
    <%= image_tag image_path('banner-delivery'), class: 'img-fluid' %>
    <br><br>
    <div class='delivery-text'>
      GIVE US A CALL OR ORDER ONLINE VIA OUR ONLINE ORDERING SYSTEM FOR JUST A $2 DOLLAR DELIVERY FEE.
      LIVE OUTSIDE OUR RANGE? WE'VE GOT YOU COVERED.
    </div>
  </div>
  <div class="col-xs-12 col-lg-6">
    <br>
    <%= link_to 'https://www.grubhub.com/', target: '_blank' do %>
      <%= image_tag image_path('delivery-grubhub'), class: 'img-fluid' %>
    <% end %>
    <div class="row">
      <div class="col-xs-6 col-lg-6">
        <%= link_to 'https://www.trycaviar.com/', target: '_blank' do %>
          <%= image_tag image_path('delivery-caviar'), class: 'img-fluid' %>
        <% end %>
      </div>
      <div class="col-xs-6 col-lg-6">
        <%= link_to 'https://www.postmates.com/', target: '_blank' do %>
          <%= image_tag image_path('delivery-postmates'), class: 'img-fluid' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-1"></div>
  <div class="col-xs-12 col-lg-5">
    <br>
    <%= image_tag image_path('weekday-deals'), class: 'img-fluid' %>
  </div>
  <div class="col-xs-12 col-lg-6">
    <br>
    <%= image_tag image_path('banner-specials'), class: 'img-fluid' %>
    <br><br>
    <div class="text-center">
      <%= image_tag image_path('mario-smash'), class: 'img-fluid smash-img' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <br>
    <%= image_tag image_path('banner-hawthorne-theatre'), class: 'img-fluid' %>
    <br><br>
    <%= link_to 'https://hawthornetheatre.com/', target: '_blank' do %>
      <%= image_tag image_path('hawthorne-theatre'), class: 'img-fluid' %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 hawthorne-text">
    ATLAS PIZZA IS ALL ABOUT THE MUSIC, AND WE'RE PROUD TO BE SERVING OUR SIGNATURE SLICES AT ALL YOUR FAVORITE HAWTHORNE SHOWS.
    AVAILABLE AT THE LOUNGE OR AT COAT CHECK.
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <br>
    <%= link_to "https://hawthornetheatre.com/", target: "_blank", class: 'hawthorne-img' do %>
      <%= image_tag image_path('hawthorne'), class:"img-fluid" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-lg-7">
    <br>
    <%= image_tag image_path('banner-follow-us'), class: "img-fluid" %>
  </div>
</div>
<div class="row">
  <div class="col-lg-1"></div>
  <div class="col-xs-12 col-lg-5 contact-text">
    <br>
    WE LOVE RECEIVING FEEDBACK AND STAYING IN TOUCH WITH OUR CUSTOMERS.
    STAY UP TO DATE WITH SPECIALS, GIVEAWAYS, AND EVENTS BY FOLLOWING OUR SOCIAL MEDIAS.
  </div>
  <div class="col-xs-6 col-lg-3">
    <%= link_to "https://www.instagram.com/atlaspizzapdx/", target: "_blank" do %>
      <%= image_tag image_path("social-instagram"), class: "img-fluid" %>
    <% end %>
  </div>
  <div class="col-xs-6 col-lg-3">
    <%= link_to "https://www.facebook.com/atlaspizzaportland/", target: "_blank" do %>
      <%= image_tag image_path("social-facebook"), class: "img-fluid" %>
    <% end %>
  </div>
</div>

app/views/pages/menu.html.erb
<div class="row menu-margins">
  <div class="col-xs-12 col-lg-4 paddingless">
    <br>
    <%= image_tag image_path("menu/1"), class: "img-fluid menu-img" %>
  </div>
  <div class="col-xs-12 col-lg-4 paddingless">
    <br>
    <%= image_tag image_path("menu/2"), class: "img-fluid menu-img" %>
  </div>
  <div class="col-xs-12 col-lg-4 paddingless">
    <br>
    <%= image_tag image_path("menu/3"), class: "img-fluid menu-img" %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-xs-12">
    EACH OF OUR LOCATIONS OFFERS MULTIPLE DRINK SELECTIONS, INCLUDING BEER, WINE, AND SOFT DRINKS.
    PLEASE CALL ONE OF OUR LOCATIONS FOR DETAILS. ASK ABOUT BEER AND WINE DELIVERY!
    <br><br>
    <div class="text-center">
      <a class="square-btn square-btn-left">ORDER</a>
      <a class="square-btn square-btn-right">CALL</a>
    </div>
    <br>
    <%= image_tag image_path("menu/menu-pizza"), class: "img-responsive menu-pizza-img" %>
  </div>
</div>

app/views/pages/partners.html.erb
<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-xs-12 col-lg-8">
    <br>
    <div class="text-center">
      <div class="page-title">
        PARTNERSHIPS
      </div>
      <br>
      Atlas Pizza believes in a strong and diverse community. We hope to help others, and in doing so create a better place for everyone to share. Here are some of the many folks we have helped raise funds for in the past.<br>
      <br>
      Cleveland High School<br>
      <br>
      Pioneer School<br>
      <br>
      VOZ Workers Rights Education Project<br>
      <br>
      4th Dimension Recovery Center<br>
      <br>
      Recovery Mentor Program<br>
      <br>
      ACLU<br>
      <br>
      Planned Parenthood<br>
      <br>
      Bradley Angel<br>
      <br>
      Immigrant and Refugee Community Organization<br>
      <br>
      PEAR<br>
      <br>
      NARAL Pro Choice<br>
      <br>
      Oregon Unite<br>
      <br>
      There have been many more and will be many more to come!<br>
    </div>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/pages/privacy.html.erb
<div>
  <br>
  <div class="page-title">
    PRIVACY NOTICE
  </div><br>
  This privacy notice discloses the privacy practices for Atlaspizzapdx.com This privacy notice applies solely to information collected by this website. It will notify you of the following:<br>
  <br>
  1. What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.<br>
  <br>
  2. What choices are available to you regarding the use of your data.<br>
  <br>
  3. The security procedures in place to protect the misuse of your information.<br>
  <br>
  4. How you can correct any inaccuracies in the information.<br>
  <br>
  <strong>Information Collection, Use, and Sharing</strong><br>
  <br>
  We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.<br>
  <br>
  We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.<br>
  <br>
  Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.<br>
  <br>
  <strong>Your Access to and Control Over Information</strong><br>
  <br>
  You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:<br>
  <br>
  * See what data we have about you, if any.<br>
  <br>
  * Change/correct any data we have about you.<br>
  <br>
  * Have us delete any data we have about you.<br>
  <br>
  * Express any concern you have about our use of your data.<br>
  <br>
  <strong>Security</strong><br>
  <br>
  We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.<br>
  <br>
  Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.<br>
  <br>
  While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.<br>
  <br>
  <strong>If you feel that we are not abiding by this privacy policy, you should <%= link_to 'contact us', contact_path %> immediately.</strong><br>
</div>